name: misty_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  logger: ^2.4.0
  get_it: ^7.7.0
  gap: ^3.0.1
  injectable: ^2.5.0
  flutter_svg: ^2.0.10+1
  easy_debounce: ^2.0.3
  dio: ^5.7.0
  intl: any
  flutter_localizations:
    sdk: flutter
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.8.1
  shared_preferences: ^2.3.2
  internet_connection_checker_plus: ^2.5.2
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.0
  envied_generator: ^0.5.4+1
  flutter_gen_runner: ^5.4.0
  injectable_generator: ^2.6.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
